version: "3"

volumes:
  postgres_volume:

services:
  pg:
    image: postgres:14-alpine3.20
    env_file:
      - ".env"
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
#    command: tail -f /dev/null
    volumes:
      - .:/project/shop
    env_file:
      - ".env"
    environment:
      DB_HOST: pg
    depends_on:
      - pg