basePath: /
definitions:
  request.CreationRequest:
    properties:
      address_id:
        type: string
      birthday:
        type: string
      gender:
        type: string
      name:
        type: string
      surname:
        type: string
    required:
    - address_id
    - birthday
    - gender
    - name
    - surname
    type: object
  response.DefaultResponse:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  response.ErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
      status:
        type: string
    type: object
host: 127.0.0.1:8000
info:
  contact: {}
  description: API Server for Chat Application
  title: Chat API
  version: "1.0"
paths:
  /clients:
    post:
      consumes:
      - application/json
      description: Create new client
      parameters:
      - description: Request payload
        in: body
        name: text
        required: true
        schema:
          $ref: '#/definitions/request.CreationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Message successfully sent
          schema:
            $ref: '#/definitions/response.DefaultResponse'
        "400":
          description: "B\tad Request"
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Create new client
      tags:
      - clients
swagger: "2.0"
