application:
  stage: "dev"
  host: "127.0.0.1"
  port: ":8000"
pg:
  name: "backend_2"
  user: "postgres"
  password: "postgres"
  host: "127.0.0.1"
  port: "5432"
  ssl_mode: "disable"
  dsn_template: "host=%s port=%s dbname=%s user=%s password=%s sslmode=%s"