application:
  stage: "local"
  host: "0.0.0.0"
  port: ":8000"
pg:
  name: "shop"
  user: "postgres"
  password: "postgres"
  host: "pg"
  port: "5432"
  ssl_mode: "disable"
  dsn_template: "host=%s port=%s dbname=%s user=%s password=%s sslmode=%s"